(define-module (dots site desktop)
  #:use-module (dots desktop)
  #:use-module (dots input)
  #:use-module (dots theme ef-dream)
  #:use-module (dots desktop niri)
  #:use-module (dots desktop pine)
  #:use-module (dots desktop eww)
  #:use-module (dots desktop waybar)
  #:use-module (dots desktop fuzzel)
  #:use-module (dots desktop alacritty)
  #:use-module (dots desktop emacs)
  #:use-module (dots desktop mako)
  #:use-module (dots desktop gtklock)
  #:use-module (dots desktop gtk)
  #:use-module (dots desktop sway)
  #:use-module (dots desktop wezterm)
  #:use-module (dots desktop vim)
  #:use-module (dots desktop swaybg)
  #:use-module (dots desktop swayidle)
  #:export (default-desktop))

(define default-desktop
  (desktop
   (compositors (list niri sway))
   (bars        (list pine eww waybar))
   (pickers     (list fuzzel))
   (terminals   (list alacritty wezterm))
   (editors     (list emacs vim))
   (notifiers   (list mako))
   (locks       (list gtklock))
   (idlers      (list swayidle))
   (wallpapers  (list swaybg))
   (toolkits    (list gtk))
   (theme       ef-dream)
   (keyboard    %default-keyboard)))
