(define-module (dots site desktop)
  #:use-module (dots desktop)
  #:use-module (dots input)
  #:use-module (dots theme ef-dream)
  #:use-module (dots home services niri)
  #:use-module (dots home services pine)
  #:use-module (dots home services eww)
  #:use-module (dots home services waybar)
  #:use-module (dots home services fuzzel)
  #:use-module (dots home services alacritty)
  #:use-module (dots home services emacs)
  #:use-module (dots home services mako)
  #:use-module (dots home services gtklock)
  #:use-module (dots home services gtk)
  #:use-module (dots home services sway)
  #:use-module (dots home services wezterm)
  #:use-module (dots home services vim)
  #:use-module (dots home services swaybg)
  #:use-module (dots home services swayidle)
  #:export (default-desktop))

(define default-desktop
  (desktop
   (compositors (list niri sway))
   (bars        (list pine eww waybar))
   (pickers     (list fuzzel))
   (terminals   (list alacritty wezterm))
   (editors     (list emacs vim))
   (notifiers   (list mako))
   (locks       (list gtklock))
   (idlers      (list swayidle))
   (wallpapers  (list swaybg))
   (toolkits    (list gtk))
   (theme       ef-dream)
   (keyboard    %default-keyboard)))
